api = "0.10"

[buildpack]
name = "DreamFactory Buildpack"

[metadata]
include-files = [
  "bin/",
  "lib/",
  "buildpack.toml",
  "README.md"
]

# Add this section to specify PHP extensions
[metadata.extensions]
pdo_sqlite = "*"
sqlite3 = "*"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "heroku-22"

[[stacks]]
id = "heroku-24" 
