[project]
id = "dreamfactory-app"
name = "DreamFactory Laravel App"
version = "1.0.0"

[build]
include = [
  "app/**",
  "bootstrap/**",
  "config/**",
  "database/**",
  "public/**",
  "resources/**",
  "routes/**",
  "storage/**",
  "vendor/**",
  ".env",
  "artisan",
  "composer.json",
  "composer.lock"
]


[[build.buildpacks]]
uri = "https://github.com/volodymyrkr-tsd/tsd-test-df"

[[build.env]]
name = "BP_PHP_VERSION"
value = "8.1.*"

[[build.env]]
name = "BP_PHP_SERVER"
value = "nginx"

[[build.env]]
name = "BP_PHP_WEB_DIR"
value = "public"
